### ISSUE TITLE
Optimisation issue

### ISSUE THREAD

**Issue by ilyida** [Calvin-LLC/nvidia-overlay-hijack#1]
After profiling the code for the overlay, around 40%-50% of the CPU time is spent on GetAsyncKeyState. This is because the input handler thread runs on an infinite loop, running thousands of times a second. I recommend you add a sleep function to the input handler, which can cause issues with the timers and make them look unsmooth. So a better way to approach it might be to run the timers separately or on another thread to the input handler.

**Comment by Calvin-LLC** [comment]
- fixed
