### ISSUE TITLE
Keyboard input

### ISSUE THREAD

**Issue by badphaze** [Calvin-LLC/nvidia-overlay-hijack#2]
I really want it, how i can fix it on that project?
Add tweak for it on src

**Comment by badphaze** [comment]
i cant use input text and other things

**Comment by Calvin-LLC** [comment]
imgui shouldn't be changed in my source, please update it yourself. the directory is: "aio overlay/lib/imgui".

**Comment by badphaze** [comment]
> imgui shouldn't be changed in my source, please update it yourself. the directory is: "aio overlay/lib/imgui".

no, you didn't understand me, I meant that in your hook there is no tracking of keystroke events in the current window, I tried to bypass it and nothing worked.

**Comment by alrohax** [comment]
did you find out how badphaze?
